# Generated by Django 6.0.7 on 2026-07-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('HIFAZ', 'Hifz (Memorization)'), ('NAZRA', 'Nazra (Reading)'), ('TAJWEED', 'Tajweed (Rules)'), ('TARBIYAH', 'Tarbiyah (Character)'), ('ISLAMIC_STUDIES', 'Islamic Studies (Theory)')], max_length=20)),
                ('surah_name', models.CharField(blank=True, max_length=100, null=True)),
                ('from_ayat', models.IntegerField(blank=True, null=True)),
                ('to_ayat', models.IntegerField(blank=True, null=True)),
                ('evaluation_grade', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('IMPROVING', 'Needs Improvement')], max_length=15)),
                ('tarbiyah_notes', models.TextField(blank=True, help_text='Character and behavior notes', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IslamicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_surah', models.CharField(blank=True, max_length=100, null=True)),
                ('current_ayat', models.IntegerField(default=1)),
                ('hifz_completed_pages', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tajweed_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], default='BEGINNER', max_length=20)),
            ],
        ),
    ]
