# Generated by Django 6.0.7 on 2026-07-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringViolationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('violation_type', models.CharField(choices=[('FACE_NOT_FOUND', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('TAB_SWITCH', 'Browser Tab Switched'), ('SPEECH_DETECTED', 'Speech/Voice Detected'), ('UNKNOWN_OBJECT', 'Restricted Object/Phone Detected')], max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='AI Model Confidence percentage (e.g. 98.50)', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('SUBJECTIVE', 'Subjective / Theory')], default='MCQ', max_length=15)),
                ('options', models.JSONField(blank=True, help_text="List of choices for MCQ, e.g. ['A', 'B', 'C', 'D']", null=True)),
                ('correct_answer', models.TextField(help_text='Correct answer text or option letter')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('ai_proctoring_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='curriculum.course')),
            ],
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_exams.exam')),
            ],
        ),
    ]
