"""
Django settings for homeschool_backend project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ta*hfy$(53=yt+k90(_ss7e4paa9z7akac10ql@4$m#!1j_a3s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    # Jazzmin must be installed before admin
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party packages
    'rest_framework',
    'corsheaders',
    'django_filters',
    'drf_spectacular',
    
    # Custom apps
    'users',
    'assessments',
    'curriculum',
    'lms',
    'islamic_studies',
    'skills_future',
    'smart_exams',
    'attendance_diary',
    'analytics',
    'accounts',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CorsMiddleware must be high up
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'homeschool_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / '..' / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'homeschool_backend.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Karachi'
USE_I18N = True
USE_TZ = True

# Static & Media files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / '..' / 'frontend' / 'dist'
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# SimpleJWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Spectacular Docs settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Bright Future Homeschooling API',
    'DESCRIPTION': 'REST API backend for Phase 1 of Bright Future Homeschooling software.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = True

# Jazzmin settings
JAZZMIN_SETTINGS = {
    "site_title": "Bright Future Homeschooling",
    "site_header": "Bright Future Admin",
    "site_brand": "Bright Future",
    "welcome_sign": "Welcome to Bright Future Homeschooling Admin",
    "copyright": "Bright Future Homeschooling Ltd",
    "search_model": ["users.User"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "API Docs (Swagger)", "url": "/api/docs/", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "users", "assessments", "curriculum", "lms", "islamic_studies",
        "skills_future", "smart_exams", "attendance_diary", "analytics", "accounts"
    ],
    "icons": {
        "users.user": "fas fa-user-shield",
        "users.studentprofile": "fas fa-user-graduate",
        "users.teacherprofile": "fas fa-chalkboard-teacher",
        "assessments.assessment": "fas fa-file-invoice",
        "assessments.assessmentresult": "fas fa-poll",
        "assessments.personalizedcurriculum": "fas fa-route",
        "curriculum.program": "fas fa-university",
        "curriculum.course": "fas fa-book-open",
        "curriculum.classroom": "fas fa-door-open",
        "curriculum.timetableslot": "fas fa-clock",
        "lms.lesson": "fas fa-chalkboard",
        "lms.assignment": "fas fa-tasks",
        "lms.assignmentsubmission": "fas fa-file-upload",
        "islamic_studies.islamicprofile": "fas fa-mosque",
        "islamic_studies.dailyprogresslog": "fas fa-calendar-check",
        "skills_future.skilltrack": "fas fa-brain",
        "skills_future.studentskillprogress": "fas fa-chart-line",
        "skills_future.projectsubmission": "fas fa-code-branch",
        "smart_exams.exam": "fas fa-paste",
        "smart_exams.question": "fas fa-question-circle",
        "smart_exams.examattempt": "fas fa-user-clock",
        "smart_exams.proctoringviolationlog": "fas fa-exclamation-triangle",
        "attendance_diary.attendance": "fas fa-check-double",
        "attendance_diary.digitaldiary": "fas fa-journal-whills",
        "analytics.studentanalyticssummary": "fas fa-chart-bar",
        "analytics.sessionengagementlog": "fas fa-eye",
        "accounts.feestructure": "fas fa-money-bill-wave",
        "accounts.invoice": "fas fa-file-invoice-dollar",
        "accounts.salaryslip": "fas fa-wallet",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_assets": True,
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-navy",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_options": [],
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
