# Generated by Django 6.0.7 on 2026-07-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='program',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structure', to='curriculum.program'),
        ),
    ]
