# Generated by Django 6.0.7 on 2026-07-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='salaryslip',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_slips', to='users.teacherprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='salaryslip',
            unique_together={('teacher', 'month')},
        ),
    ]
