# Generated by Django 6.0.7 on 2026-07-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_url', models.URLField(help_text='Link to GitHub, Scratch, or cloud drive folder')),
                ('teacher_review', models.TextField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ROBOTICS', 'Robotics'), ('PYTHON', 'Python Coding'), ('SCRATCH', 'Scratch coding'), ('GRAPHIC_DESIGN', 'Graphic Design'), ('DIGITAL_SKILLS', 'Digital Skills')], max_length=20)),
                ('level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percent', models.IntegerField(default=0, help_text='Percentage 0-100')),
                ('completed_projects_count', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
