# Generated by Django 6.0.7 on 2026-07-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills_future', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_projects', to='users.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='skilltrack',
            unique_together={('name', 'level')},
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_future.skilltrack'),
        ),
        migrations.AddField(
            model_name='studentskillprogress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='studentskillprogress',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills_future.skilltrack'),
        ),
        migrations.AlterUniqueTogether(
            name='studentskillprogress',
            unique_together={('student', 'track')},
        ),
    ]
