# Generated by Django 6.0.7 on 2026-07-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('islamic_studies', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='islamicprofile',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='islamic_profile', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='dailyprogresslog',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='islamic_studies.islamicprofile'),
        ),
    ]
