# Generated by Django 6.0.7 on 2026-07-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('attention_percentage', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnalyticsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('understanding_index', models.DecimalField(decimal_places=2, default=0.0, help_text='AI estimated understanding rating (0.0 - 100.0)', max_digits=5)),
                ('concentration_score', models.DecimalField(decimal_places=2, default=0.0, help_text='AI calculated concentration rating (0.0 - 100.0)', max_digits=5)),
                ('engagement_score', models.DecimalField(decimal_places=2, default=0.0, help_text='AI calculated class engagement rating (0.0 - 100.0)', max_digits=5)),
                ('academic_strength', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_weakness', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
