# Generated by Django 6.0.7 on 2026-07-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('LEAVE', 'On Leave')], default='PRESENT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('homework_notes', models.TextField(blank=True, null=True)),
                ('announcements', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
