# Generated by Django 6.0.7 on 2026-07-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance_diary', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='digitaldiary',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='curriculum.classroom'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date'), ('teacher', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='digitaldiary',
            unique_together={('classroom', 'date')},
        ),
    ]
